INSERT INTO (ID, AUTHOR, ISBN, PUBLISH_DATE, TITLE) VALUES (1,'James','ISBN','2022-05-01', '1TITLE');
INSERT INTO (ID, AUTHOR, ISBN, PUBLISH_DATE, TITLE) VALUES (1,'John','ISBN','2020-05-01', '2TITLE');
INSERT INTO (ID, AUTHOR, ISBN, PUBLISH_DATE, TITLE) VALUES (1,'Rob','ISBN','2019-05-01', '3TITLE');
INSERT INTO (ID, AUTHOR, ISBN, PUBLISH_DATE, TITLE) VALUES (1,'Lars','ISBN','2019-05-01', '4TITLE');
